Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -111,10 +111,10 @@ jobs:
       - run:
           name: Smoke Test
           command: HTTPCODE=`curl -s -o /dev/null -w "%{http_code}" https://whispering-beach-97898.herokuapp.com/`
-          if [ "$HTTPCODE" -ne 200 ];then
-              echo "heroku app not responding, failing deploy"
-              exit 1
-          fi
+            if [ "$HTTPCODE" -ne 200 ];then
+                echo "heroku app not responding, failing deploy"
+                exit 1
+            fi
 
 workflows:
   version: 2
